INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('huiguorou', 2, 'chinese recipe', 'hengwu');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('shizitou', 2, 'chinese recipe', 'hengwu');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('tutou', 2, 'chinese recipe', 'hengwu');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('mapodoufu', 2, 'chinese recipe', 'hengwu');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('jianjiaofeichang', 2, 'chinese recipe', 'hengwu');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('guobaorou', 2, 'chinese northeast recipe', 'david');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('xiaojiduimogu', 2, 'chinese northeast recipe', 'david');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('lidalicai', 2, 'italian  recipe', 'haozhang');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('broccoli', 2, 'italian  broccoli recipe', 'haozhang');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('sugar cake', 2, 'sugar cake', 'haozhang');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('Grandma’s Fettuccini Alfredo', 3, 'italian recipe', 'haozhang');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('tuna1', 1, 'best tuna1', 'haozhang');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('tuna2', 2, 'best tuna2', 'haozhang');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('tuna3', 3, 'best tuna3', 'haozhang');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('tuna4', 4, 'best tuna4', 'haozhang');
INSERT INTO recipe.Recipe (title, number_of_serving, description, username) VALUES ('tuna5', 5, 'best tuna5', 'haozhang');